/**
 * Seed: province_experiences
 * Tier 0 (issue #46). Phase 1 seeded the pilot (California, Texas, Wyoming,
 * Rhode Island, Beijing, Hong Kong); Phase 3 below rounds out every remaining
 * US state and China province/region with real, well-known landmarks. All
 * experiences within a province are worth equal points (see
 * calculateTier0ProvinceExploration in points.js). See
 * docs/features/tier-0-nations.md for the sourcing approach and caveats.
 */

const experiences = [
  // California
  { province_code: 'US-CA', name: 'Golden Gate Bridge' },
  { province_code: 'US-CA', name: 'Alcatraz Island' },
  { province_code: 'US-CA', name: 'Hollywood Walk of Fame' },
  { province_code: 'US-CA', name: 'Yosemite National Park' },
  { province_code: 'US-CA', name: 'Disneyland Park' },
  { province_code: 'US-CA', name: 'Griffith Observatory' },
  { province_code: 'US-CA', name: 'Balboa Park' },
  { province_code: 'US-CA', name: 'Sequoia National Park' },
  // Texas
  { province_code: 'US-TX', name: 'The Alamo' },
  { province_code: 'US-TX', name: 'San Antonio River Walk' },
  { province_code: 'US-TX', name: 'Space Center Houston' },
  { province_code: 'US-TX', name: 'Reunion Tower' },
  { province_code: 'US-TX', name: 'AT&T Stadium' },
  { province_code: 'US-TX', name: 'Texas State Capitol' },
  { province_code: 'US-TX', name: 'Big Bend National Park' },
  { province_code: 'US-TX', name: 'Fort Worth Stockyards' },
  // Wyoming
  { province_code: 'US-WY', name: 'Yellowstone National Park' },
  { province_code: 'US-WY', name: 'Grand Teton National Park' },
  { province_code: 'US-WY', name: 'Devils Tower National Monument' },
  { province_code: 'US-WY', name: 'Wyoming State Capitol' },
  { province_code: 'US-WY', name: 'Fort Laramie National Historic Site' },
  // Rhode Island
  { province_code: 'US-RI', name: 'The Breakers' },
  { province_code: 'US-RI', name: 'Newport Cliff Walk' },
  { province_code: 'US-RI', name: 'Rhode Island State House' },
  { province_code: 'US-RI', name: 'Beavertail Lighthouse' },
  { province_code: 'US-RI', name: 'Roger Williams Park Zoo' },
  // Beijing
  { province_code: 'CN-BJ', name: 'Forbidden City' },
  { province_code: 'CN-BJ', name: 'Great Wall at Badaling' },
  { province_code: 'CN-BJ', name: 'Temple of Heaven' },
  { province_code: 'CN-BJ', name: 'Tiananmen Square' },
  { province_code: 'CN-BJ', name: 'Summer Palace' },
  { province_code: 'CN-BJ', name: "Beijing National Stadium (Bird's Nest)" },
  // Hong Kong (no cities — experiences only, per issue #46)
  { province_code: 'CN-HK', name: 'Victoria Peak' },
  { province_code: 'CN-HK', name: 'Star Ferry Harbour Crossing' },
  { province_code: 'CN-HK', name: 'Tian Tan Buddha' },
  { province_code: 'CN-HK', name: 'Hong Kong Disneyland' },
  { province_code: 'CN-HK', name: 'Ocean Park Hong Kong' },

  // ── Tier 0 Phase 3 (issue #46): remaining US states ─────────────────────
  { province_code: 'US-AL', name: 'U.S. Space & Rocket Center' },
  { province_code: 'US-AL', name: 'Rosa Parks Museum' },
  { province_code: 'US-AL', name: 'USS Alabama Battleship Memorial Park' },
  { province_code: 'US-AL', name: 'Vulcan Statue' },
  { province_code: 'US-AL', name: 'Gulf State Park' },
  { province_code: 'US-AK', name: 'Denali National Park' },
  { province_code: 'US-AK', name: 'Kenai Fjords National Park' },
  { province_code: 'US-AK', name: 'Mendenhall Glacier' },
  { province_code: 'US-AK', name: 'Alaska SeaLife Center' },
  { province_code: 'US-AK', name: 'Chugach State Park' },
  { province_code: 'US-AZ', name: 'Grand Canyon National Park' },
  { province_code: 'US-AZ', name: 'Antelope Canyon' },
  { province_code: 'US-AZ', name: 'Sedona Red Rocks' },
  { province_code: 'US-AZ', name: 'Saguaro National Park' },
  { province_code: 'US-AZ', name: 'Monument Valley' },
  { province_code: 'US-AR', name: 'Hot Springs National Park' },
  { province_code: 'US-AR', name: 'Crystal Bridges Museum of American Art' },
  { province_code: 'US-AR', name: 'Buffalo National River' },
  { province_code: 'US-AR', name: 'Clinton Presidential Library' },
  { province_code: 'US-AR', name: 'Ozark National Forest' },
  { province_code: 'US-CO', name: 'Rocky Mountain National Park' },
  { province_code: 'US-CO', name: 'Garden of the Gods' },
  { province_code: 'US-CO', name: 'Red Rocks Amphitheatre' },
  { province_code: 'US-CO', name: 'Mesa Verde National Park' },
  { province_code: 'US-CO', name: 'Pikes Peak' },
  { province_code: 'US-CT', name: 'Mystic Seaport' },
  { province_code: 'US-CT', name: 'Yale University Campus' },
  { province_code: 'US-CT', name: 'Mark Twain House' },
  { province_code: 'US-CT', name: 'Gillette Castle' },
  { province_code: 'US-CT', name: 'Mohegan Sun' },
  { province_code: 'US-DE', name: 'Rehoboth Beach' },
  { province_code: 'US-DE', name: 'Winterthur Museum' },
  { province_code: 'US-DE', name: 'Fort Delaware' },
  { province_code: 'US-DE', name: 'Nemours Estate' },
  { province_code: 'US-DE', name: 'Delaware Art Museum' },
  { province_code: 'US-DC', name: 'Lincoln Memorial' },
  { province_code: 'US-DC', name: 'Smithsonian National Air and Space Museum' },
  { province_code: 'US-DC', name: 'U.S. Capitol' },
  { province_code: 'US-DC', name: 'Washington Monument' },
  { province_code: 'US-DC', name: 'The National Mall' },
  { province_code: 'US-DC', name: 'The White House' },
  { province_code: 'US-FL', name: 'Walt Disney World' },
  { province_code: 'US-FL', name: 'Everglades National Park' },
  { province_code: 'US-FL', name: 'Kennedy Space Center' },
  { province_code: 'US-FL', name: 'South Beach Miami' },
  { province_code: 'US-FL', name: 'St. Augustine Historic District' },
  { province_code: 'US-FL', name: 'Universal Studios Florida' },
  { province_code: 'US-GA', name: 'Georgia Aquarium' },
  { province_code: 'US-GA', name: 'Stone Mountain Park' },
  { province_code: 'US-GA', name: 'Savannah Historic District' },
  { province_code: 'US-GA', name: 'Martin Luther King Jr. National Historical Park' },
  { province_code: 'US-GA', name: 'World of Coca-Cola' },
  { province_code: 'US-HI', name: 'Pearl Harbor National Memorial' },
  { province_code: 'US-HI', name: 'Haleakalā National Park' },
  { province_code: 'US-HI', name: 'Hawaii Volcanoes National Park' },
  { province_code: 'US-HI', name: 'Waikiki Beach' },
  { province_code: 'US-HI', name: 'Diamond Head' },
  { province_code: 'US-HI', name: 'Nā Pali Coast' },
  { province_code: 'US-ID', name: 'Sun Valley Resort' },
  { province_code: 'US-ID', name: 'Shoshone Falls' },
  { province_code: 'US-ID', name: 'Craters of the Moon National Monument' },
  { province_code: 'US-ID', name: 'Snake River Canyon' },
  { province_code: 'US-ID', name: 'Idaho State Capitol' },
  { province_code: 'US-IL', name: 'Willis Tower' },
  { province_code: 'US-IL', name: 'Millennium Park (Cloud Gate)' },
  { province_code: 'US-IL', name: 'Art Institute of Chicago' },
  { province_code: 'US-IL', name: 'Field Museum' },
  { province_code: 'US-IL', name: 'Navy Pier' },
  { province_code: 'US-IL', name: "Lincoln's Home National Historic Site" },
  { province_code: 'US-IN', name: 'Indianapolis Motor Speedway' },
  { province_code: 'US-IN', name: 'Indiana Dunes National Park' },
  { province_code: 'US-IN', name: "Children's Museum of Indianapolis" },
  { province_code: 'US-IN', name: 'West Baden Springs Hotel' },
  { province_code: 'US-IN', name: 'Conner Prairie' },
  { province_code: 'US-IA', name: 'Field of Dreams Movie Site' },
  { province_code: 'US-IA', name: 'Iowa State Capitol' },
  { province_code: 'US-IA', name: 'Amana Colonies' },
  { province_code: 'US-IA', name: 'Effigy Mounds National Monument' },
  { province_code: 'US-IA', name: 'Herbert Hoover Presidential Library' },
  { province_code: 'US-KS', name: 'Monument Rocks' },
  { province_code: 'US-KS', name: 'Cosmosphere' },
  { province_code: 'US-KS', name: 'Tallgrass Prairie National Preserve' },
  { province_code: 'US-KS', name: 'Brown v. Board of Education National Historical Park' },
  { province_code: 'US-KS', name: 'Dodge City Boot Hill Museum' },
  { province_code: 'US-KY', name: 'Mammoth Cave National Park' },
  { province_code: 'US-KY', name: 'Churchill Downs' },
  { province_code: 'US-KY', name: 'Kentucky Bourbon Trail' },
  { province_code: 'US-KY', name: 'Cumberland Falls' },
  { province_code: 'US-KY', name: 'Louisville Slugger Museum' },
  { province_code: 'US-LA', name: 'French Quarter' },
  { province_code: 'US-LA', name: 'Mardi Gras World' },
  { province_code: 'US-LA', name: 'Louisiana State Capitol' },
  { province_code: 'US-LA', name: 'Oak Alley Plantation' },
  { province_code: 'US-LA', name: 'Caddo Lake' },
  { province_code: 'US-ME', name: 'Acadia National Park' },
  { province_code: 'US-ME', name: 'Portland Head Light' },
  { province_code: 'US-ME', name: 'Old Orchard Beach' },
  { province_code: 'US-ME', name: "L.L.Bean Flagship Store" },
  { province_code: 'US-ME', name: 'Baxter State Park' },
  { province_code: 'US-MD', name: 'Fort McHenry National Monument' },
  { province_code: 'US-MD', name: 'Chesapeake Bay Maritime Museum' },
  { province_code: 'US-MD', name: 'Antietam National Battlefield' },
  { province_code: 'US-MD', name: 'Baltimore Inner Harbor' },
  { province_code: 'US-MD', name: 'Assateague Island' },
  { province_code: 'US-MA', name: 'Freedom Trail' },
  { province_code: 'US-MA', name: 'Fenway Park' },
  { province_code: 'US-MA', name: 'Plymouth Rock' },
  { province_code: 'US-MA', name: 'Harvard University Campus' },
  { province_code: 'US-MA', name: 'Cape Cod National Seashore' },
  { province_code: 'US-MI', name: 'Mackinac Island' },
  { province_code: 'US-MI', name: 'Sleeping Bear Dunes National Lakeshore' },
  { province_code: 'US-MI', name: 'Henry Ford Museum' },
  { province_code: 'US-MI', name: 'Detroit Institute of Arts' },
  { province_code: 'US-MI', name: 'Isle Royale National Park' },
  { province_code: 'US-MN', name: 'Mall of America' },
  { province_code: 'US-MN', name: 'Minnehaha Falls' },
  { province_code: 'US-MN', name: 'Boundary Waters Canoe Area' },
  { province_code: 'US-MN', name: 'Split Rock Lighthouse' },
  { province_code: 'US-MN', name: 'Voyageurs National Park' },
  { province_code: 'US-MS', name: 'Vicksburg National Military Park' },
  { province_code: 'US-MS', name: 'Natchez Trace Parkway' },
  { province_code: 'US-MS', name: 'Elvis Presley Birthplace' },
  { province_code: 'US-MS', name: 'Gulf Islands National Seashore' },
  { province_code: 'US-MS', name: 'Mississippi Civil Rights Museum' },
  { province_code: 'US-MO', name: 'Gateway Arch' },
  { province_code: 'US-MO', name: 'Missouri Botanical Garden' },
  { province_code: 'US-MO', name: "Mark Twain Boyhood Home" },
  { province_code: 'US-MO', name: 'Lake of the Ozarks' },
  { province_code: 'US-MO', name: 'City Museum' },
  { province_code: 'US-MT', name: 'Glacier National Park' },
  { province_code: 'US-MT', name: 'Yellowstone National Park (North Entrance)' },
  { province_code: 'US-MT', name: 'Big Sky Resort' },
  { province_code: 'US-MT', name: 'Museum of the Rockies' },
  { province_code: 'US-MT', name: 'Flathead Lake' },
  { province_code: 'US-NE', name: 'Chimney Rock National Historic Site' },
  { province_code: 'US-NE', name: 'Henry Doorly Zoo' },
  { province_code: 'US-NE', name: 'Scotts Bluff National Monument' },
  { province_code: 'US-NE', name: 'Carhenge' },
  { province_code: 'US-NE', name: 'Strategic Air Command & Aerospace Museum' },
  { province_code: 'US-NV', name: 'Las Vegas Strip' },
  { province_code: 'US-NV', name: 'Hoover Dam' },
  { province_code: 'US-NV', name: 'Red Rock Canyon' },
  { province_code: 'US-NV', name: 'Lake Tahoe' },
  { province_code: 'US-NV', name: 'Fremont Street Experience' },
  { province_code: 'US-NH', name: 'Mount Washington' },
  { province_code: 'US-NH', name: 'Franconia Notch State Park' },
  { province_code: 'US-NH', name: 'Lake Winnipesaukee' },
  { province_code: 'US-NH', name: 'Strawbery Banke Museum' },
  { province_code: 'US-NH', name: 'Old Man of the Mountain Historic Site' },
  { province_code: 'US-NJ', name: 'Liberty State Park' },
  { province_code: 'US-NJ', name: 'Atlantic City Boardwalk' },
  { province_code: 'US-NJ', name: 'Cape May Historic District' },
  { province_code: 'US-NJ', name: 'Thomas Edison National Historical Park' },
  { province_code: 'US-NJ', name: 'Six Flags Great Adventure' },
  { province_code: 'US-NM', name: 'Carlsbad Caverns National Park' },
  { province_code: 'US-NM', name: 'White Sands National Park' },
  { province_code: 'US-NM', name: 'Santa Fe Plaza' },
  { province_code: 'US-NM', name: 'Taos Pueblo' },
  { province_code: 'US-NM', name: 'Bandelier National Monument' },
  { province_code: 'US-NY', name: 'Statue of Liberty' },
  { province_code: 'US-NY', name: 'Empire State Building' },
  { province_code: 'US-NY', name: 'Niagara Falls' },
  { province_code: 'US-NY', name: 'Central Park' },
  { province_code: 'US-NY', name: 'Times Square' },
  { province_code: 'US-NY', name: 'Metropolitan Museum of Art' },
  { province_code: 'US-NC', name: 'Great Smoky Mountains National Park' },
  { province_code: 'US-NC', name: 'Wright Brothers National Memorial' },
  { province_code: 'US-NC', name: 'Biltmore Estate' },
  { province_code: 'US-NC', name: 'Outer Banks' },
  { province_code: 'US-NC', name: 'Blue Ridge Parkway' },
  { province_code: 'US-ND', name: 'Theodore Roosevelt National Park' },
  { province_code: 'US-ND', name: 'Fargo Air Museum' },
  { province_code: 'US-ND', name: 'International Peace Garden' },
  { province_code: 'US-ND', name: 'Fort Union Trading Post National Historic Site' },
  { province_code: 'US-ND', name: 'Knife River Indian Villages' },
  { province_code: 'US-OH', name: 'Rock and Roll Hall of Fame' },
  { province_code: 'US-OH', name: 'Cedar Point' },
  { province_code: 'US-OH', name: 'Pro Football Hall of Fame' },
  { province_code: 'US-OH', name: 'Cincinnati Zoo' },
  { province_code: 'US-OH', name: 'Hocking Hills State Park' },
  { province_code: 'US-OK', name: 'National Cowboy & Western Heritage Museum' },
  { province_code: 'US-OK', name: 'Oklahoma City National Memorial' },
  { province_code: 'US-OK', name: 'Chickasaw National Recreation Area' },
  { province_code: 'US-OK', name: 'Tallgrass Prairie Preserve' },
  { province_code: 'US-OR', name: 'Crater Lake National Park' },
  { province_code: 'US-OR', name: 'Columbia River Gorge' },
  { province_code: 'US-OR', name: "Powell's City of Books" },
  { province_code: 'US-OR', name: 'Multnomah Falls' },
  { province_code: 'US-OR', name: 'Oregon Coast' },
  { province_code: 'US-PA', name: 'Liberty Bell' },
  { province_code: 'US-PA', name: 'Independence Hall' },
  { province_code: 'US-PA', name: 'Gettysburg National Military Park' },
  { province_code: 'US-PA', name: 'Hersheypark' },
  { province_code: 'US-PA', name: 'Fallingwater' },
  { province_code: 'US-SC', name: 'Fort Sumter National Monument' },
  { province_code: 'US-SC', name: 'Myrtle Beach' },
  { province_code: 'US-SC', name: 'Charleston Historic District' },
  { province_code: 'US-SC', name: 'Congaree National Park' },
  { province_code: 'US-SC', name: 'Hilton Head Island' },
  { province_code: 'US-SD', name: 'Mount Rushmore National Memorial' },
  { province_code: 'US-SD', name: 'Badlands National Park' },
  { province_code: 'US-SD', name: 'Crazy Horse Memorial' },
  { province_code: 'US-SD', name: 'Custer State Park' },
  { province_code: 'US-SD', name: 'Wind Cave National Park' },
  { province_code: 'US-TN', name: 'Great Smoky Mountains National Park (Gatlinburg)' },
  { province_code: 'US-TN', name: 'Graceland' },
  { province_code: 'US-TN', name: 'Country Music Hall of Fame' },
  { province_code: 'US-TN', name: 'Ryman Auditorium' },
  { province_code: 'US-TN', name: 'Tennessee Aquarium' },
  { province_code: 'US-UT', name: 'Zion National Park' },
  { province_code: 'US-UT', name: 'Bryce Canyon National Park' },
  { province_code: 'US-UT', name: 'Arches National Park' },
  { province_code: 'US-UT', name: 'Salt Lake Temple Square' },
  { province_code: 'US-UT', name: 'Bonneville Salt Flats' },
  { province_code: 'US-VT', name: "Ben & Jerry's Factory" },
  { province_code: 'US-VT', name: 'Shelburne Museum' },
  { province_code: 'US-VT', name: 'Green Mountain National Forest' },
  { province_code: 'US-VT', name: 'Church Street Marketplace' },
  { province_code: 'US-VT', name: 'Lake Champlain' },
  { province_code: 'US-VA', name: 'Colonial Williamsburg' },
  { province_code: 'US-VA', name: 'Shenandoah National Park' },
  { province_code: 'US-VA', name: 'Monticello' },
  { province_code: 'US-VA', name: 'Arlington National Cemetery' },
  { province_code: 'US-VA', name: 'Virginia Beach Boardwalk' },
  { province_code: 'US-WA', name: 'Space Needle' },
  { province_code: 'US-WA', name: 'Mount Rainier National Park' },
  { province_code: 'US-WA', name: 'Pike Place Market' },
  { province_code: 'US-WA', name: 'Olympic National Park' },
  { province_code: 'US-WA', name: 'Museum of Pop Culture' },
  { province_code: 'US-WV', name: 'New River Gorge National Park' },
  { province_code: 'US-WV', name: 'Harpers Ferry National Historical Park' },
  { province_code: 'US-WV', name: 'Seneca Rocks' },
  { province_code: 'US-WV', name: 'The Greenbrier Resort' },
  { province_code: 'US-WI', name: 'Wisconsin Dells' },
  { province_code: 'US-WI', name: 'Door County' },
  { province_code: 'US-WI', name: 'Taliesin' },
  { province_code: 'US-WI', name: 'Lambeau Field' },
  { province_code: 'US-WI', name: 'House on the Rock' },

  // ── Tier 0 Phase 3 (issue #46): remaining China provinces/regions ──────
  // Fewer entries per province than the US list (3-4 vs 5-8) — reflects lower
  // confidence in an exhaustive landmark list per province; these are all
  // genuinely famous, well-documented sites, not invented.
  { province_code: 'CN-AH', name: 'Huangshan (Yellow Mountain)' },
  { province_code: 'CN-AH', name: 'Hongcun Ancient Village' },
  { province_code: 'CN-AH', name: 'Jiuhua Mountain' },
  { province_code: 'CN-CQ', name: 'Dazu Rock Carvings' },
  { province_code: 'CN-CQ', name: 'Hongyadong' },
  { province_code: 'CN-CQ', name: 'Ciqikou Ancient Town' },
  { province_code: 'CN-CQ', name: 'Wulong Karst' },
  { province_code: 'CN-FJ', name: 'Gulangyu Island' },
  { province_code: 'CN-FJ', name: 'Fujian Tulou' },
  { province_code: 'CN-FJ', name: 'Wuyi Mountain' },
  { province_code: 'CN-GS', name: 'Mogao Caves' },
  { province_code: 'CN-GS', name: 'Jiayuguan Pass' },
  { province_code: 'CN-GS', name: 'Zhangye Danxia Landform' },
  { province_code: 'CN-GD', name: 'Canton Tower' },
  { province_code: 'CN-GD', name: 'Chimelong Ocean Kingdom' },
  { province_code: 'CN-GD', name: 'Kaiping Diaolou' },
  { province_code: 'CN-GX', name: 'Li River / Guilin Karst Landscape' },
  { province_code: 'CN-GX', name: 'Longji Rice Terraces' },
  { province_code: 'CN-GX', name: 'Detian Waterfall' },
  { province_code: 'CN-GZ', name: 'Huangguoshu Waterfall' },
  { province_code: 'CN-GZ', name: 'Zhijin Cave' },
  { province_code: 'CN-GZ', name: 'Qianling Mountain' },
  { province_code: 'CN-HI', name: 'Sanya Beaches' },
  { province_code: 'CN-HI', name: 'Yalong Bay' },
  { province_code: 'CN-HI', name: 'Nanshan Temple' },
  { province_code: 'CN-HE', name: 'Chengde Mountain Resort' },
  { province_code: 'CN-HE', name: 'Shanhaiguan Great Wall' },
  { province_code: 'CN-HE', name: 'Zhangjiakou' },
  { province_code: 'CN-HL', name: 'Harbin Ice and Snow World' },
  { province_code: 'CN-HL', name: 'Zhalong Nature Reserve' },
  { province_code: 'CN-HL', name: 'Yabuli Ski Resort' },
  { province_code: 'CN-HA', name: 'Shaolin Temple' },
  { province_code: 'CN-HA', name: 'Longmen Grottoes' },
  { province_code: 'CN-HA', name: 'Yin Xu Ruins' },
  { province_code: 'CN-HB', name: 'Yellow Crane Tower' },
  { province_code: 'CN-HB', name: 'Three Gorges Dam' },
  { province_code: 'CN-HB', name: 'Wudang Mountains' },
  { province_code: 'CN-HN', name: 'Zhangjiajie National Forest Park' },
  { province_code: 'CN-HN', name: 'Fenghuang Ancient Town' },
  { province_code: 'CN-HN', name: 'Yueyang Tower' },
  { province_code: 'CN-JS', name: "Humble Administrator's Garden" },
  { province_code: 'CN-JS', name: 'Zhouzhuang Water Town' },
  { province_code: 'CN-JS', name: 'Xuanwu Lake' },
  { province_code: 'CN-JX', name: 'Lushan National Park' },
  { province_code: 'CN-JX', name: 'Jingdezhen Porcelain Capital' },
  { province_code: 'CN-JX', name: 'Poyang Lake' },
  { province_code: 'CN-JL', name: 'Changbai Mountain' },
  { province_code: 'CN-JL', name: 'Songhua Lake' },
  { province_code: 'CN-JL', name: "Puppet Emperor's Palace" },
  { province_code: 'CN-LN', name: 'Shenyang Imperial Palace' },
  { province_code: 'CN-LN', name: 'Bingyu Valley' },
  { province_code: 'CN-NM', name: 'Xilamuren Grassland' },
  { province_code: 'CN-NM', name: 'Genghis Khan Mausoleum' },
  { province_code: 'CN-NM', name: 'Kubuqi Desert' },
  { province_code: 'CN-NX', name: 'Shapotou Desert' },
  { province_code: 'CN-NX', name: 'Western Xia Tombs' },
  { province_code: 'CN-NX', name: 'Shuidonggou' },
  { province_code: 'CN-QH', name: 'Qinghai Lake' },
  { province_code: 'CN-QH', name: "Ta'er Monastery" },
  { province_code: 'CN-QH', name: 'Chaka Salt Lake' },
  { province_code: 'CN-SN', name: 'Terracotta Army' },
  { province_code: 'CN-SN', name: "Xi'an City Wall" },
  { province_code: 'CN-SN', name: 'Huashan Mountain' },
  { province_code: 'CN-SD', name: 'Mount Tai' },
  { province_code: 'CN-SD', name: 'Confucius Temple, Qufu' },
  { province_code: 'CN-SH', name: 'The Bund' },
  { province_code: 'CN-SH', name: 'Oriental Pearl Tower' },
  { province_code: 'CN-SH', name: 'Yu Garden' },
  { province_code: 'CN-SX', name: 'Yungang Grottoes' },
  { province_code: 'CN-SX', name: 'Pingyao Ancient City' },
  { province_code: 'CN-SX', name: 'Hukou Waterfall' },
  { province_code: 'CN-SC', name: 'Chengdu Research Base of Giant Panda Breeding' },
  { province_code: 'CN-SC', name: 'Jiuzhaigou Valley' },
  { province_code: 'CN-SC', name: 'Leshan Giant Buddha' },
  { province_code: 'CN-TJ', name: 'Italian Style Town' },
  { province_code: 'CN-TJ', name: 'Ancient Culture Street' },
  { province_code: 'CN-XJ', name: 'Tianshan Tianchi' },
  { province_code: 'CN-XJ', name: 'Kashgar Old City' },
  { province_code: 'CN-XJ', name: 'Karakul Lake' },
  { province_code: 'CN-XZ', name: 'Potala Palace' },
  { province_code: 'CN-XZ', name: 'Jokhang Temple' },
  { province_code: 'CN-XZ', name: 'Namtso Lake' },
  { province_code: 'CN-YN', name: 'Lijiang Old Town' },
  { province_code: 'CN-YN', name: 'Shilin Stone Forest' },
  { province_code: 'CN-YN', name: 'Erhai Lake' },
  { province_code: 'CN-ZJ', name: 'West Lake' },
  { province_code: 'CN-ZJ', name: 'Wuzhen Water Town' },
  { province_code: 'CN-ZJ', name: 'Qiandao Lake' },
  { province_code: 'CN-MO', name: "Ruins of St. Paul's" },
  { province_code: 'CN-MO', name: 'Macau Tower' },
  { province_code: 'CN-MO', name: 'Senado Square' },
];

exports.seed = async function (knex) {
  const crypto = require('crypto');

  const existing = await knex('province_experiences').count('* as count').first();
  if (parseInt(existing.count, 10) > 0) {
    console.log('Province experiences already seeded, skipping.');
    return;
  }

  const rows = experiences.map(e => ({ id: crypto.randomUUID(), ...e }));
  const batchSize = 50;
  for (let i = 0; i < rows.length; i += batchSize) {
    await knex('province_experiences').insert(rows.slice(i, i + batchSize));
  }
  console.log(`Seeded ${rows.length} province experiences.`);
};

exports.experiences = experiences;
